package reverse;
// Generated 7 nov 2022 21:01:25 by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos implements java.io.Serializable {

	private String idn;
	private String apenom;
	private String direcc;
	private String prov;
	private String email;
	private Set notases = new HashSet(0);

	public Alumnos() {
	}

	public Alumnos(String idn) {
		this.idn = idn;
	}

	public Alumnos(String idn, String apenom, String direcc, String prov, String email, Set notases) {
		this.idn = idn;
		this.apenom = apenom;
		this.direcc = direcc;
		this.prov = prov;
		this.email = email;
		this.notases = notases;
	}

	public String getIdn() {
		return this.idn;
	}

	public void setIdn(String idn) {
		this.idn = idn;
	}

	public String getApenom() {
		return this.apenom;
	}

	public void setApenom(String apenom) {
		this.apenom = apenom;
	}

	public String getDirecc() {
		return this.direcc;
	}

	public void setDirecc(String direcc) {
		this.direcc = direcc;
	}

	public String getProv() {
		return this.prov;
	}

	public void setProv(String prov) {
		this.prov = prov;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getNotases() {
		return this.notases;
	}

	public void setNotases(Set notases) {
		this.notases = notases;
	}

}
