package reverse;
// Generated 7 nov 2022 21:01:25 by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Asignaturas generated by hbm2java
 */
public class Asignaturas implements java.io.Serializable {

	private int cdn;
	private String nombre;
	private Set notases = new HashSet(0);

	public Asignaturas() {
	}

	public Asignaturas(int cdn) {
		this.cdn = cdn;
	}

	public Asignaturas(int cdn, String nombre, Set notases) {
		this.cdn = cdn;
		this.nombre = nombre;
		this.notases = notases;
	}

	public int getCdn() {
		return this.cdn;
	}

	public void setCdn(int cdn) {
		this.cdn = cdn;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getNotases() {
		return this.notases;
	}

	public void setNotases(Set notases) {
		this.notases = notases;
	}

}
